services:
  nginx:
    image: nginx:1.29.3
    ports:
    #  - "8080:80"
    #  - "4343:443"
    - "8080:443"
    volumes:
      - nginx_data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
  fast-api:
    image: fast-api
    build:
      dockerfile: ./Dockerfile


volumes:
   nginx_data: